#! /bin/sh

#killall -q dunst
#killall -q picom
#killall -q sxhkd
#killall -q polybar
pgrep -x sxhkd > /dev/null || sxhkd &
#while pfrep -u $UID -x dunst >/dev/null; do sleep 1; done
#while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
#while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
#while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done
#while pfrep -u $UID -x fehbg >/dev/null; do sleep 1; done

# Autostart Apps
#dunst & 
#picom & 
#sxhkd &
~/.config/polybar/launch.sh
#~/.fehbg

# Colors
FOCUSED_BORDER_COLOR="#F9F6EE"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#2587AC"

bspc monitor -d I II III IV V 

bspc config border_width          2
bspc config window_gap            12
#Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
#bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$FOCUSED_BORDER_COLOR"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Application Rules
#bspc rule -a st-256color      desktop='^1' follow=on
#bspc rule -a firefox          desktop='^2' 
#bspc rule -a Firefox-esr      desktop='^2' 
#bspc rule -a TelegramDesktop  desktop='^4'
#bspc rule -a Zathura          desktop='^5' state=tiled

feh --bg-fill /home/lmntr1x/.config/screenshot/thevalley.jpg
picom --experimental-backends &
bspc config border_width 1.5
xsetroot -cursor_name left_ptr &
VBoxClient --clipboard
VBoxClient --vmsvga
